export const ADD_BUN_PRICE = 'ADD_BUN_PRICE';
export const REMOVE_BUN_PRICE = 'REMOVE_BUN_PRICE';
export const ADD_INGREDIENT_PRICE = 'ADD_INGREDIENT_PRICE';
export const REMOVE_INGREDIENT_PRICE = 'REMOVE_INGREDIENT_PRICE';
export const CLEAR_TOTAL_PRICE = 'CLEAR_TOTAL_PRICE';